version: '3'

services:
  payload:
    # image: node:20-slim
    build:
      dockerfile: Dockerfile
    container_name: payload-cms
    ports:
      - '4000:3000'
    volumes:
      - ./media:/app/media
      - .:/home/node/app
      # - node_modules:/home/node/app/node_modules
    # working_dir: /home/node/app/
    # command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm dev"
    # command: sh -c "npm install && npm run dev"
    # restart: unless-stopped
    env_file:
      - .env.production
    networks:
      - pgsql
      - net-payload-cms

volumes:
  data:
  node_modules:

networks:
  pgsql:
    external: true
  net-payload-cms:
    name: net-payload-cms
    driver: bridge
