/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'etta-media': EttaMedia;
    'etta-work-experience': EttaWorkExperience;
    'etta-projects': EttaProject;
    'etta-course': EttaCourse;
    'etta-exploration': EttaExploration;
    'franz-media': FranzMedia;
    'franz-blogs': FranzBlog;
    'franz-work-experience': FranzWorkExperience;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'etta-media': EttaMediaSelect<false> | EttaMediaSelect<true>;
    'etta-work-experience': EttaWorkExperienceSelect<false> | EttaWorkExperienceSelect<true>;
    'etta-projects': EttaProjectsSelect<false> | EttaProjectsSelect<true>;
    'etta-course': EttaCourseSelect<false> | EttaCourseSelect<true>;
    'etta-exploration': EttaExplorationSelect<false> | EttaExplorationSelect<true>;
    'franz-media': FranzMediaSelect<false> | FranzMediaSelect<true>;
    'franz-blogs': FranzBlogsSelect<false> | FranzBlogsSelect<true>;
    'franz-work-experience': FranzWorkExperienceSelect<false> | FranzWorkExperienceSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-media".
 */
export interface EttaMedia {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-work-experience".
 */
export interface EttaWorkExperience {
  id: number;
  active?: boolean | null;
  image?: (number | null) | EttaMedia;
  position: string;
  organization: string;
  location?: string | null;
  startDate: string;
  endDate: string;
  responsibilities?: TextFieldBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextFieldBlock".
 */
export interface TextFieldBlock {
  textField?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'text-field-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-projects".
 */
export interface EttaProject {
  id: number;
  active?: boolean | null;
  image?: (number | null) | EttaMedia;
  projectName: string;
  projectType: 'Website' | 'Mobile';
  role: string;
  description: string;
  tags?:
    | (
        | 'Taiga'
        | 'Postman'
        | 'MySQL'
        | 'Google Sheet'
        | 'TEMAN'
        | 'Jira'
        | 'Confluence'
        | 'Swagger'
        | 'DBeaver'
        | 'Spreadsheet'
        | 'Microsoft Office'
      )[]
    | null;
  detail?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-course".
 */
export interface EttaCourse {
  id: number;
  active?: boolean | null;
  image: number | EttaMedia;
  courseName: string;
  courseType: string;
  periode?: string | null;
  description?: string | null;
  links?: LinkBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBlock".
 */
export interface LinkBlock {
  text: string;
  url: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'link-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-exploration".
 */
export interface EttaExploration {
  id: number;
  active?: boolean | null;
  image: number | EttaMedia;
  name: string;
  appLink: string;
  description: string;
  links?: LinkBlock[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franz-media".
 */
export interface FranzMedia {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franz-blogs".
 */
export interface FranzBlog {
  id: number;
  slug: string;
  isPublished?: boolean | null;
  title: string;
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franz-work-experience".
 */
export interface FranzWorkExperience {
  id: number;
  active?: boolean | null;
  position: string;
  organization: string;
  location?: string | null;
  startDate: string;
  endDate?: string | null;
  untilNow?: boolean | null;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'etta-media';
        value: number | EttaMedia;
      } | null)
    | ({
        relationTo: 'etta-work-experience';
        value: number | EttaWorkExperience;
      } | null)
    | ({
        relationTo: 'etta-projects';
        value: number | EttaProject;
      } | null)
    | ({
        relationTo: 'etta-course';
        value: number | EttaCourse;
      } | null)
    | ({
        relationTo: 'etta-exploration';
        value: number | EttaExploration;
      } | null)
    | ({
        relationTo: 'franz-media';
        value: number | FranzMedia;
      } | null)
    | ({
        relationTo: 'franz-blogs';
        value: number | FranzBlog;
      } | null)
    | ({
        relationTo: 'franz-work-experience';
        value: number | FranzWorkExperience;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-media_select".
 */
export interface EttaMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-work-experience_select".
 */
export interface EttaWorkExperienceSelect<T extends boolean = true> {
  active?: T;
  image?: T;
  position?: T;
  organization?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  responsibilities?:
    | T
    | {
        'text-field-block'?: T | TextFieldBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TextFieldBlock_select".
 */
export interface TextFieldBlockSelect<T extends boolean = true> {
  textField?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-projects_select".
 */
export interface EttaProjectsSelect<T extends boolean = true> {
  active?: T;
  image?: T;
  projectName?: T;
  projectType?: T;
  role?: T;
  description?: T;
  tags?: T;
  detail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-course_select".
 */
export interface EttaCourseSelect<T extends boolean = true> {
  active?: T;
  image?: T;
  courseName?: T;
  courseType?: T;
  periode?: T;
  description?: T;
  links?:
    | T
    | {
        'link-block'?: T | LinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkBlock_select".
 */
export interface LinkBlockSelect<T extends boolean = true> {
  text?: T;
  url?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "etta-exploration_select".
 */
export interface EttaExplorationSelect<T extends boolean = true> {
  active?: T;
  image?: T;
  name?: T;
  appLink?: T;
  description?: T;
  links?:
    | T
    | {
        'link-block'?: T | LinkBlockSelect<T>;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franz-media_select".
 */
export interface FranzMediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franz-blogs_select".
 */
export interface FranzBlogsSelect<T extends boolean = true> {
  slug?: T;
  isPublished?: T;
  title?: T;
  excerpt?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "franz-work-experience_select".
 */
export interface FranzWorkExperienceSelect<T extends boolean = true> {
  active?: T;
  position?: T;
  organization?: T;
  location?: T;
  startDate?: T;
  endDate?: T;
  untilNow?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?:
    | (
        | 'abap'
        | 'apex'
        | 'azcli'
        | 'bat'
        | 'c'
        | 'clojure'
        | 'coffee'
        | 'cpp'
        | 'csharp'
        | 'csp'
        | 'css'
        | 'dart'
        | 'dockerfile'
        | 'fsharp'
        | 'go'
        | 'graphql'
        | 'handlebars'
        | 'html'
        | 'ini'
        | 'java'
        | 'javascript'
        | 'json'
        | 'julia'
        | 'kotlin'
        | 'less'
        | 'lua'
        | 'markdown'
        | 'msdax'
        | 'mysql'
        | 'objective-c'
        | 'pascal'
        | 'perl'
        | 'pgsql'
        | 'php'
        | 'plaintext'
        | 'postiats'
        | 'powerquery'
        | 'powershell'
        | 'pug'
        | 'python'
        | 'r'
        | 'razor'
        | 'redis'
        | 'redshift'
        | 'ruby'
        | 'rust'
        | 'sb'
        | 'scheme'
        | 'scss'
        | 'shell'
        | 'sol'
        | 'sql'
        | 'st'
        | 'swift'
        | 'tcl'
        | 'typescript'
        | 'vb'
        | 'xml'
        | 'yaml'
      )
    | null;
  code?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "UploadBlock".
 */
export interface UploadBlock {
  upload?: (number | null) | FranzMedia;
  id?: string | null;
  blockName?: string | null;
  blockType: 'upload-block';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}